print("Jose Angelo L. Labrador")
print("Tanza,Boac,Marinduque")
print("July 26, 2001")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("Second Year - 2C")